##################################################
# zmj-user aliyun Deployment
##################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zmj-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${artifactId}
  template:
    metadata:
      labels:
        app: ${artifactId}
    spec:
      containers:
        - name: zmj-user
          image: harbor.zhengmeiji.com.cn:881/cloud/zmj/${artifactId}:latest
          imagePullPolicy: Always
          ports:
            - protocol: TCP
              containerPort: 80
          env:
            - name: PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
---
##################################################
# zmj-user aliyun Service
##################################################
apiVersion: v1
kind: Service
metadata:
  name: ${artifactId}-svc
spec:
  ports:
    - name: server
      port: 80
  selector:
    app: ${artifactId}
  type: NodePort
---
##################################################
# zmj-user aliyun Ingress
##################################################
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${artifactId}-ing
spec:
  rules:
    - host: ${artifactIdZmjRemove}.biz.zhengmeiji.com.cn
      http:
        paths:
          - backend:
              serviceName: ${artifactId}-svc
              servicePort: 80
