FROM openjdk:8-jdk-alpine
MAINTAINER yuhai yuhai313@163.com
ENV TZ Asia/Shanghai
EXPOSE 8080
COPY . /
COPY ./config/font/SimHei.ttf /usr/share/fonts/simhei.ttf 
WORKDIR /
RUN chmod +x /bin/*.sh && echo "http://mirrors.aliyun.com/alpine/v3.6/main" > /etc/apk/repositories \
    && echo "http://mirrors.aliyun.com/alpine/v3.6/community" >> /etc/apk/repositories \
    && apk update upgrade \
    && apk add --no-cache procps unzip curl bash tzdata \
    && apk add ttf-dejavu \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone
CMD [ "./bin/startDocker.sh" ]